# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  release:
    types: [ published ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish-to-gallery:
    needs: build
    runs-on: ubuntu-latest
    environment: publish
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish
      # API key generated in PSGallery
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
          BUILD_VERSION: ${{github.ref_name}}
        shell: pwsh
        run: |
          ./Build.ps1
          Publish-Module -path ./ -NuGetApiKey $env:NUGET_API_KEY -Verbose          
